// examples/svelte-example.svelte
<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { CashierSDK } from '../lib/CashierSDK';
    import { PaymentService } from '../PaymentService';
    import type { PayInTransactionData, PayInResponse } from '../PaymentService';

    let isLoading = false;
    let paymentStatus = '';
    let errorMessage = '';
    let paymentData: PayInResponse | null = null;

    let cashierSDK: CashierSDK | null = null;
    let paymentService: PaymentService | null = null;

    let formData = {
        amount: 100,
        currency: 'USD',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '+1234567890',
        country: 'US',
        dateOfBirth: '1990-01-01',
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        postalCode: '10001'
    };

    onMount(() => {
        paymentService = new PaymentService({
            apiBaseUrl: 'https://your-api-endpoint.com',
            apiKey: 'your-api-key'
        });

        cashierSDK = new CashierSDK({
            apiBaseUrl: 'https://your-api-endpoint.com',
            borderRadius: '12px',
            backgroundColor: '#ffffff',
            device: 'auto'
        });

        cashierSDK.on('paymentSuccess', handlePaymentSuccess);
        cashierSDK.on('paymentError', handlePaymentError);
        cashierSDK.on('paymentCanceled', handlePaymentCanceled);
        cashierSDK.on('iframeOpened', handleIframeOpened);
        cashierSDK.on('iframeClosed', handleIframeClosed);
    });

    onDestroy(() => {
        if (cashierSDK) {
            cashierSDK.destroy();
        }
    });

    function handlePaymentSuccess(data: any) {
        paymentStatus = 'success';
        console.log('Payment successful:', data);
    }

    function handlePaymentError(data: any) {
        paymentStatus = 'error';
        errorMessage = data.message || 'Payment failed';
        console.error('Payment error:', data);
    }

    function handlePaymentCanceled(data: any) {
        paymentStatus = 'canceled';
        console.log('Payment canceled:', data);
    }

    function handleIframeOpened(data: any) {
        console.log('Payment iframe opened:', data);
    }

    function handleIframeClosed(data: any) {
        console.log('Payment iframe closed:', data);
        if (paymentStatus === '') {
            paymentStatus = 'closed';
        }
    }

    async function initiateCardPayment() {
        if (!paymentService || !cashierSDK) return;

        isLoading = true;
        paymentStatus = '';
        errorMessage = '';

        try {
            const transactionData: PayInTransactionData = {
                customer: {
                    firstName: formData.firstName,
                    lastName: formData.lastName,
                    externalUserId: `user_${Date.now()}`,
                    email: formData.email,
                    phoneNumber: formData.phoneNumber,
                    country: formData.country,
                    dateOfBirth: formData.dateOfBirth,
                    billing: {
                        address: formData.address,
                        city: formData.city,
                        state: formData.state,
                        countryCode: formData.country,
                        postalCode: formData.postalCode
                    }
                },
                returnUrls: {
                    success: `${window.location.origin}/payment-success`,
                    failure: `${window.location.origin}/payment-failure`
                },
                kycVerified: false,
                previousTransactionCount: 0,
                webhook: {
                    url: 'https://your-webhook-endpoint.com/webhook'
                },
                currency: formData.currency,
                orderId: paymentService.generateOrderId(),
                amount: formData.amount
            };

            const response = await paymentService.createPayInTransaction(transactionData);
            paymentData = response;

            cashierSDK.openPaymentIframe(response.iframeUrls.card);

        } catch (error) {
            errorMessage = error instanceof Error ? error.message : 'Failed to create payment';
            paymentStatus = 'error';
        } finally {
            isLoading = false;
        }
    }

    async function initiateAPMPayment() {
        if (!paymentData || !cashierSDK) return;
        cashierSDK.openPaymentIframe(paymentData.iframeUrls.apm);
    }

    function resetPayment() {
        paymentStatus = '';
        errorMessage = '';
        paymentData = null;
    }
</script>

<div class="payment-container">
    <h1>Svelte Payment Integration</h1>

    {#if paymentStatus === 'success'}
        <div class="status-card success">
            <h2>✅ Payment Successful!</h2>
            <p>Your payment has been processed successfully.</p>
            <button on:click={resetPayment}>Make Another Payment</button>
        </div>
    {:else if paymentStatus === 'error'}
        <div class="status-card error">
            <h2>❌ Payment Failed</h2>
            <p>{errorMessage}</p>
            <button on:click={resetPayment}>Try Again</button>
        </div>
    {:else if paymentStatus === 'canceled'}
        <div class="status-card warning">
            <h2>⚠️ Payment Canceled</h2>
            <p>The payment was canceled by the user.</p>
            <button on:click={resetPayment}>Try Again</button>
        </div>
    {:else}
        <form class="payment-form" on:submit|preventDefault={initiateCardPayment}>
            <div class="form-group">
                <label for="amount">Amount</label>
                <input
                        id="amount"
                        type="number"
                        bind:value={formData.amount}
                        min="1"
                        required
                />
            </div>

            <div class="form-group">
                <label for="currency">Currency</label>
                <select id="currency" bind:value={formData.currency} required>
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                    <option value="GBP">GBP</option>
                </select>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="firstName">First Name</label>
                    <input
                            id="firstName"
                            type="text"
                            bind:value={formData.firstName}
                            required
                    />
                </div>
                <div class="form-group">
                    <label for="lastName">Last Name</label>
                    <input
                            id="lastName"
                            type="text"
                            bind:value={formData.lastName}
                            required
                    />
                </div>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input
                        id="email"
                        type="email"
                        bind:value={formData.email}
                        required
                />
            </div>

            <div class="form-group">
                <label for="phone">Phone Number</label>
                <input
                        id="phone"
                        type="tel"
                        bind:value={formData.phoneNumber}
                        required
                />
            </div>

            <div class="form-group">
                <label for="address">Address</label>
                <input
                        id="address"
                        type="text"
                        bind:value={formData.address}
                        required
                />
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="city">City</label>
                    <input
                            id="city"
                            type="text"
                            bind:value={formData.city}
                            required
                    />
                </div>
                <div class="form-group">
                    <label for="state">State</label>
                    <input
                            id="state"
                            type="text"
                            bind:value={formData.state}
                            required
                    />
                </div>
                <div class="form-group">
                    <label for="postalCode">Postal Code</label>
                    <input
                            id="postalCode"
                            type="text"
                            bind:value={formData.postalCode}
                            required
                    />
                </div>
            </div>

            <div class="payment-buttons">
                <button
                        type="submit"
                        disabled={isLoading}
                        class="btn btn-primary"
                >
                    {isLoading ? 'Processing...' : 'Pay with Card'}
                </button>

                {#if paymentData}
                    <button
                            type="button"
                            on:click={initiateAPMPayment}
                            class="btn btn-secondary"
                    >
                        Alternative Payment Methods
                    </button>
                {/if}
            </div>
        </form>
    {/if}
</div>

<style>
    .payment-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 2rem;
        font-family: 'Inter', sans-serif;
    }

    h1 {
        text-align: center;
        color: #1f2937;
        margin-bottom: 2rem;
    }

    .payment-form {
        background: white;
        padding: 2rem;
        border-radius: 12px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .form-row {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
        gap: 1rem;
    }

    label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: 500;
        color: #374151;
    }

    input, select {
        width: 100%;
        padding: 0.75rem;
        border: 1px solid #d1d5db;
        border-radius: 6px;
        font-size: 1rem;
    }

    input:focus, select:focus {
        outline: none;
        border-color: #3b82f6;
        box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
    }

    .payment-buttons {
        display: flex;
        gap: 1rem;
        margin-top: 2rem;
    }

    .btn {
        flex: 1;
        padding: 0.75rem 1.5rem;
        border: none;
        border-radius: 6px;
        font-size: 1rem;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s;
    }

    .btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    .btn-primary {
        background-color: #3b82f6;
        color: white;
    }

    .btn-primary:hover:not(:disabled) {
        background-color: #2563eb;
    }

    .btn-secondary {
        background-color: #6b7280;
        color: white;
    }

    .btn-secondary:hover:not(:disabled) {
        background-color: #4b5563;
    }

    .status-card {
        padding: 2rem;
        border-radius: 12px;
        text-align: center;
    }

    .status-card.success {
        background-color: #f0fdf4;
        border: 1px solid #bbf7d0;
        color: #166534;
    }

    .status-card.error {
        background-color: #fef2f2;
        border: 1px solid #fecaca;
        color: #dc2626;
    }

    .status-card.warning {
        background-color: #fffbeb;
        border: 1px solid #fed7aa;
        color: #d97706;
    }

    .status-card h2 {
        margin: 0 0 1rem 0;
    }

    .status-card button {
        margin-top: 1rem;
        padding: 0.75rem 1.5rem;
        background-color: #3b82f6;
        color: white;
        border: none;
        border-radius: 6px;
        cursor: pointer;
    }
</style>

// examples/vue-example.vue
<template>
  <div class="container">
    <h1 class="title">Vue Payment Integration</h1>

    <div v-if="paymentStatus === 'success'" class="status-card success-card">
      <h2>✅ Payment Successful!</h2>
      <p>Your payment has been processed successfully.</p>
      <button @click="resetPayment" class="button primary-button reset-button">
        Make Another Payment
      </button>
    </div>

    <div v-else-if="paymentStatus === 'error'" class="status-card error-card">
      <h2>❌ Payment Failed</h2>
      <p>{{ errorMessage }}</p>
      <button @click="resetPayment" class="button primary-button reset-button">
        Try Again
      </button>
    </div>

    <div v-else-if="paymentStatus === 'canceled'" class="status-card warning-card">
      <h2>⚠️ Payment Canceled</h2>
      <p>The payment was canceled by the user.</p>
      <button @click="resetPayment" class="button primary-button reset-button">
        Try Again
      </button>
    </div>

    <div v-else class="form">
      <form @submit="initiateCardPayment">
        <div class="form-group">
          <label class="label">Amount</label>
          <input
              v-model.number="formData.amount"
              type="number"
              name="amount"
              class="input"
              min="1"
              required
          />
        </div>

        <div class="form-group">
          <label class="label">Currency</label>
          <select v-model="formData.currency" name="currency" class="input" required>
            <option value="USD">USD</option>
            <option value="EUR">EUR</option>
            <option value="GBP">GBP</option>
          </select>
        </div>

        <div class="form-row">
          <div class="form-group">
            <label class="label">First Name</label>
            <input
                v-model="formData.firstName"
                type="text"
                name="firstName"
                class="input"
                required
            />
          </div>
          <div class="form-group">
            <label class="label">Last Name</label>
            <input
                v-model="formData.lastName"
                type="text"
                name="lastName"
                class="input"
                required
            />
          </div>
        </div>

        <div class="form-group">
          <label class="label">Email</label>
          <input
              v-model="formData.email"
              type="email"
              name="email"
              class="input"
              required
          />
        </div>

        <div class="form-group">
          <label class="label">Phone Number</label>
          <input
              v-model="formData.phoneNumber"
              type="tel"
              name="phoneNumber"
              class="input"
              required
          />
        </div>

        <div class="form-group">
          <label class="label">Address</label>
          <input
              v-model="formData.address"
              type="text"
              name="address"
              class="input"
              required
          />
        </div>

        <div class="form-row">
          <div class="form-group">
            <label class="label">City</label>
            <input
                v-model="formData.city"
                type="text"
                name="city"
                class="input"
                required
            />
          </div>
          <div class="form-group">
            <label class="label">State</label>
            <input
                v-model="formData.state"
                type="text"
                name="state"
                class="input"
                required
            />
          </div>
          <div class="form-group">
            <label class="label">Postal Code</label>
            <input
                v-model="formData.postalCode"
                type="text"
                name="postalCode"
                class="input"
                required
            />
          </div>
        </div>

        <div class="button-group">
          <button
              type="submit"
              :disabled="isLoading"
              :class="['button', 'primary-button', { 'disabled-button': isLoading }]"
          >
            {{ isLoading ? 'Processing...' : 'Pay with Card' }}
          </button>

          <button
              v-if="paymentData"
              type="button"
              @click="initiateAPMPayment"
              class="button secondary-button"
          >
            Alternative Payment Methods
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
const CashierSDK = {
  constructor(config) {
    this.config = config;
    this.eventHandlers = {};
    return this;
  },
  on(event, callback) {
    if (!this.eventHandlers[event]) {
      this.eventHandlers[event] = [];
    }
    this.eventHandlers[event].push(callback);
  },
  openPaymentIframe(url) {
    setTimeout(() => {
      this.emit('iframeOpened', { url });
      setTimeout(() => {
        const outcomes = ['paymentSuccess', 'paymentError', 'paymentCanceled'];
        const outcome = outcomes[Math.floor(Math.random() * outcomes.length)];
        this.emit(outcome, {
          paymentId: 'test_' + Date.now(),
          amount: 100,
          status: outcome === 'paymentSuccess' ? 'completed' : 'failed'
        });
      }, 3000);
    }, 500);
  },
  emit(event, data) {
    if (this.eventHandlers[event]) {
      this.eventHandlers[event].forEach(callback => callback(data));
    }
  },
  destroy() {
    this.eventHandlers = {};
  }
};

const PaymentService = {
  constructor(config) {
    this.config = config;
    return this;
  },
  async createPayInTransaction(data) {
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
      paymentId: 'pay_' + Date.now(),
      status: 'pending',
      iframeUrls: {
        card: 'https://mock-payment-url.com/card',
        apm: 'https://mock-payment-url.com/apm'
      }
    };
  },
  generateOrderId() {
    return 'order_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
  }
};

export default {
  name: 'PaymentIntegration',
  data() {
    return {
      isLoading: false,
      paymentStatus: '',
      errorMessage: '',
      paymentData: null,
      cashierSDK: null,
      paymentService: null,
      formData: {
        amount: 100,
        currency: 'USD',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phoneNumber: '+1234567890',
        country: 'US',
        dateOfBirth: '1990-01-01',
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        postalCode: '10001'
      }
    };
  },
  mounted() {
    this.initializeServices();
  },
  beforeUnmount() {
    if (this.cashierSDK) {
      this.cashierSDK.destroy();
    }
  },
  methods: {
    initializeServices() {
      const paymentServiceInstance = Object.create(PaymentService);
      PaymentService.constructor.call(paymentServiceInstance, {
        apiBaseUrl: 'https://your-api-endpoint.com',
        apiKey: 'your-api-key'
      });

      const cashierSDKInstance = Object.create(CashierSDK);
      CashierSDK.constructor.call(cashierSDKInstance, {
        apiBaseUrl: 'https://your-api-endpoint.com',
        borderRadius: '12px',
        backgroundColor: '#ffffff',
        device: 'auto'
      });

      cashierSDKInstance.on('paymentSuccess', this.handlePaymentSuccess);
      cashierSDKInstance.on('paymentError', this.handlePaymentError);
      cashierSDKInstance.on('paymentCanceled', this.handlePaymentCanceled);
      cashierSDKInstance.on('iframeOpened', this.handleIframeOpened);
      cashierSDKInstance.on('iframeClosed', this.handleIframeClosed);

      this.paymentService = paymentServiceInstance;
      this.cashierSDK = cashierSDKInstance;
    },
    handlePaymentSuccess(data) {
      this.paymentStatus = 'success';
      console.log('Payment successful:', data);
    },
    handlePaymentError(data) {
      this.paymentStatus = 'error';
      this.errorMessage = data.message || 'Payment failed';
      console.error('Payment error:', data);
    },
    handlePaymentCanceled(data) {
      this.paymentStatus = 'canceled';
      console.log('Payment canceled:', data);
    },
    handleIframeOpened(data) {
      console.log('Payment iframe opened:', data);
    },
    handleIframeClosed(data) {
      console.log('Payment iframe closed:', data);
      if (this.paymentStatus === '') {
        this.paymentStatus = 'closed';
      }
    },
    async initiateCardPayment(e) {
      e.preventDefault();
      if (!this.paymentService || !this.cashierSDK) return;

      this.isLoading = true;
      this.paymentStatus = '';
      this.errorMessage = '';

      try {
        const transactionData = {
          customer: {
            firstName: this.formData.firstName,
            lastName: this.formData.lastName,
            externalUserId: `user_${Date.now()}`,
            email: this.formData.email,
            phoneNumber: this.formData.phoneNumber,
            country: this.formData.country,
            dateOfBirth: this.formData.dateOfBirth,
            billing: {
              address: this.formData.address,
              city: this.formData.city,
              state: this.formData.state,
              countryCode: this.formData.country,
              postalCode: this.formData.postalCode
            }
          },
          returnUrls: {
            success: `${window.location.origin}/payment-success`,
            failure: `${window.location.origin}/payment-failure`
          },
          kycVerified: false,
          previousTransactionCount: 0,
          webhook: {
            url: 'https://your-webhook-endpoint.com/webhook'
          },
          currency: this.formData.currency,
          orderId: this.paymentService.generateOrderId(),
          amount: this.formData.amount
        };

        const response = await this.paymentService.createPayInTransaction(transactionData);
        this.paymentData = response;

        this.cashierSDK.openPaymentIframe(response.iframeUrls.card);
      } catch (error) {
        this.errorMessage = error instanceof Error ? error.message : 'Failed to create payment';
        this.paymentStatus = 'error';
      } finally {
        this.isLoading = false;
      }
    },
    initiateAPMPayment() {
      if (!this.paymentData || !this.cashierSDK) return;
      this.cashierSDK.openPaymentIframe(this.paymentData.iframeUrls.apm);
    },
    resetPayment() {
      this.paymentStatus = '';
      this.errorMessage = '';
      this.paymentData = null;
    }
  }
};
</script>

<style scoped>
.container {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
  font-family: Inter, sans-serif;
}

.title {
  text-align: center;
  color: #1f2937;
  margin-bottom: 2rem;
}

.form {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.form-group {
  margin-bottom: 1rem;
}

.form-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
}

.label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: #374151;
}

.input {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 1rem;
  box-sizing: border-box;
}

.button-group {
  display: flex;
  gap: 1rem;
  margin-top: 2rem;
}

.button {
  flex: 1;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.primary-button {
  background-color: #3b82f6;
  color: white;
}

.primary-button:hover:not(.disabled-button) {
  background-color: #2563eb;
}

.secondary-button {
  background-color: #6b7280;
  color: white;
}

.secondary-button:hover {
  background-color: #4b5563;
}

.disabled-button {
  opacity: 0.5;
  cursor: not-allowed;
}

.status-card {
  padding: 2rem;
  border-radius: 12px;
  text-align: center;
}

.success-card {
  background-color: #f0fdf4;
  border: 1px solid #bbf7d0;
  color: #166534;
}

.error-card {
  background-color: #fef2f2;
  border: 1px solid #fecaca;
  color: #dc2626;
}

.warning-card {
  background-color: #fffbeb;
  border: 1px solid #fed7aa;
  color: #d97706;
}

.reset-button {
  margin-top: 1rem;
}
</style>
